languages:
- code: EN
  name: English
- code: RU
  name: Russian

exchanges:
  barong: barong.events.system
  peatio: peatio.events.model

keychain:
  barong:
    algorithm: RS256
    value: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE0VlQ3bytSWkdtSDZIR2ZjTVNXNgo5WjU5MXdGK3BJSGZQTTNxTDUxTzlXTnA1M3Avbno3VUMwZ2ZXQzEzR3AzUHU5Q3YzUXVGSjRyYjlhN2VuWmZMCnJrSzV6VUZGRm1NSXhoTmYzV3lDdktCcHVoS0p5SG5aejAzVEVPNXpaaCtiZ3pobXRhNkswK2wxai9GQVlXTy8KNklNeXFudVBCVjVodkhIRzJJNmNyTDA3a0RFNUw0NWNicENqc29YbnlLYnJJRUROeitqblVzZUovd3dVaDlIYQo5ZU8rNW85YmdwaHBuSFloalIwMmFtd0N4SGpTNXN3ZkJqOFMvQXRjQzlOOXptcThHUXRqT3QwQUlkTkdrWStJCk9aRTV2Q01zbCtHVHVtNWJabm4wZTNrdHkxTlRYSTdHMHNWMnRWck4yWHJTSHZ0VWJlWXIwditEelRKTUJ0VSsKZHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

  peatio:
    algorithm: RS256
    value: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE0VlQ3bytSWkdtSDZIR2ZjTVNXNgo5WjU5MXdGK3BJSGZQTTNxTDUxTzlXTnA1M3Avbno3VUMwZ2ZXQzEzR3AzUHU5Q3YzUXVGSjRyYjlhN2VuWmZMCnJrSzV6VUZGRm1NSXhoTmYzV3lDdktCcHVoS0p5SG5aejAzVEVPNXpaaCtiZ3pobXRhNkswK2wxai9GQVlXTy8KNklNeXFudVBCVjVodkhIRzJJNmNyTDA3a0RFNUw0NWNicENqc29YbnlLYnJJRUROeitqblVzZUovd3dVaDlIYQo5ZU8rNW85YmdwaHBuSFloalIwMmFtd0N4SGpTNXN3ZkJqOFMvQXRjQzlOOXptcThHUXRqT3QwQUlkTkdrWStJCk9aRTV2Q01zbCtHVHVtNWJabm4wZTNrdHkxTlRYSTdHMHNWMnRWck4yWHJTSHZ0VWJlWXIwditEelRKTUJ0VSsKZHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

events:
- name: Email Confirmation
  key: user.email.confirmation.token
  exchange: barong
  templates:
    EN:
      subject: Registration Confirmation
      template_path: templates/en/email_confirmation.tpl
    RU:
      subject: Подтверждение Регистрации
      template_path: templates/ru/email_confirmation.tpl

- name: Password Reset
  key: user.password.reset.token
  exchange: barong
  templates:
    EN:
      subject: Password Reset
      template_path: templates/en/password_reset.tpl
    RU:
      subject: Сброс Пароля
      template_path: templates/ru/password_reset.tpl

- name: Deposit Accepted
  key: deposit.updated
  exchange: peatio
  expression: changes.state == "submitted" && record.state == "accepted"
  templates:
    EN:
      subject: Deposit Accepted
      template_path: templates/en/deposit_accepted.tpl

- name: Withdrawal Succeed
  key: withdraw.updated
  exchange: peatio
  expression: changes.state in ["errored", "confirming"] && record.state == "succeed"
  templates:
    EN:
      subject: Withdrawal Succeed
      template_path: templates/en/withdraw_succeed.tpl

- name: New Beneficiary
  key: beneficiary.created
  exchange: peatio
  templates:
    EN:
      subject: New Beneficiary
      template_path: templates/en/new_beneficiary.tpl
